# Generated by Django 5.0.6 on 2024-06-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('details_link', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('agency', models.CharField(max_length=255)),
                ('agency_logo', models.URLField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('land_surface', models.CharField(blank=True, max_length=50, null=True)),
                ('interior_surface', models.CharField(blank=True, max_length=50, null=True)),
                ('swimming_pool', models.CharField(blank=True, max_length=100, null=True)),
                ('construction_year', models.CharField(blank=True, max_length=4, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('accessible_to_foreigners', models.BooleanField(default=False)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('toilets', models.IntegerField(blank=True, null=True)),
                ('aircon', models.BooleanField(default=False)),
                ('general_features', models.TextField(blank=True, null=True)),
                ('indoor_features', models.TextField(blank=True, null=True)),
                ('outdoor_features', models.TextField(blank=True, null=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Land', 'Land'), ('Commercial Land', 'Commercial Land')], max_length=50)),
                ('ref', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PricePerSquareMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Land', 'Land'), ('Commercial Land', 'Commercial Land')], max_length=50)),
                ('price_per_square_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.region')),
            ],
        ),
    ]
