# Generated by Django 5.0.6 on 2024-06-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='interior_surface',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
