# Generated by Django 5.0.6 on 2024-06-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_interior_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='interior_surface_numeric',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='interior_surface',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
