# Generated by Django 5.0.6 on 2024-06-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_rename_interior_surface_numeric_property_interior_surface_clean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='interior_surface_clean',
        ),
    ]
