# Generated by Django 5.0.6 on 2024-06-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_interior_surface_clean_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='interior_surface_clean',
        ),
    ]
