# Generated by Django 5.0.6 on 2024-06-25 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PropertyPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='properties.property')),
            ],
        ),
    ]
