# Generated by Django 5.0.6 on 2024-06-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_sold_propertypricehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='land_surface',
        ),
        migrations.AddField(
            model_name='property',
            name='land_surface_decimal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
