# Generated by Django 5.0.6 on 2024-06-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_rename_land_surface_decimal_property_land_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
