# Generated by Django 5.0.6 on 2024-06-28 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_property_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 25, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
