# Generated by Django 5.0.6 on 2024-06-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='agency',
            new_name='agency_name',
        ),
    ]
