# Generated by Django 5.0.6 on 2024-06-28 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_rename_agency_property_agency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.agency'),
            preserve_default=False,
        ),
    ]
